//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTECH_WebReviewCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIVIET()
        {
            this.LINKLIENKETs = new HashSet<LINKLIENKET>();
        }
    
        public int MABAIVIET { get; set; }
        public string TENBAIVIET { get; set; }
        public string HINHANH { get; set; }
        public string NOIDUNG { get; set; }
        public string TACGIA { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> MATRANGTHAI { get; set; }
        public Nullable<int> MADANHMUC { get; set; }
        public Nullable<int> MALOAI { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual LOAIBAIDANG LOAIBAIDANG { get; set; }
        public virtual TRANGTHAIBAIDANG TRANGTHAIBAIDANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINKLIENKET> LINKLIENKETs { get; set; }
    }
}
