//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTECH_WebReviewCongNghe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbReviewDoCongNgheFTECHEntities : DbContext
    {
        public dbReviewDoCongNgheFTECHEntities()
            : base("name=dbReviewDoCongNgheFTECHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAIVIET> BAIVIET { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<DANHMUC> DANHMUC { get; set; }
        public virtual DbSet<DOITAC> DOITAC { get; set; }
        public virtual DbSet<LINKLIENKET> LINKLIENKET { get; set; }
        public virtual DbSet<LOAIBAIDANG> LOAIBAIDANG { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<TRANGTHAIBAIDANG> TRANGTHAIBAIDANG { get; set; }
    }
}
