//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTECH_WebReviewCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOITAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOITAC()
        {
            this.LINKLIENKETs = new HashSet<LINKLIENKET>();
        }
    
        public int MADOITAC { get; set; }
        public string TENCONGTY { get; set; }
        public string CANHANDAIDIEN { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string MASOTHUE { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> THOIGIANBATDAU { get; set; }
        public string HOPDONG { get; set; }
        public string PHUONGTHUCTHANHTOAN { get; set; }
        public string SOTAIKHOAN { get; set; }
        public string NGANHANG { get; set; }
        public string TENTAIKHOAN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINKLIENKET> LINKLIENKETs { get; set; }
    }
}
