//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTECH_WebReviewCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKLIENKET
    {
        public int IDLINKLIENKET { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
        public Nullable<int> MADOITAC { get; set; }
        public Nullable<int> MABAIVIET { get; set; }
        public string LINKLIENKET1 { get; set; }
        public Nullable<decimal> TILEHOAHONG { get; set; }
        public Nullable<decimal> DOANHTHUBANHANG { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual BAIVIET BAIVIET { get; set; }
        public virtual DOITAC DOITAC { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
