//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTECH_WebReviewCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAIBAIDANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANGTHAIBAIDANG()
        {
            this.BAIVIETs = new HashSet<BAIVIET>();
        }
    
        public int MATRANGTHAI { get; set; }
        public string TRANGTHAIBAIDANG1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET> BAIVIETs { get; set; }
    }
}
